name: deploy-webeditor
on:
  workflow_dispatch:
    inputs:
      deployCommit:
        description: 'Commit (empty to deploy the latest commit on master)'
        required: true
        default: 'latest'
jobs:
  deploy:
    name: Deploy webeditor
    runs-on: ubuntu-latest
    steps:
      - id: determine-webeditor-commit
        name: Determine webeditor commit to deploy
        uses: actions/github-script@v5
        with:
          script: |
            if ('${{ github.event.inputs.deployCommit }}' == 'latest') {
              const response = github.rest.git.getRef({
                owner: 'ByteLegend',
                repo: 'ByteLegend,
                ref: 'master'
              })
              console.log(`Commit to deploy: ${response.object.sha}`)
              core.setOutput('deploy-commit', response.object.sha)
            } else {
              console.log(`Commit to deploy: ${{ github.event.inputs.deployCommit }}`)
              core.setOutput('deploy-commit', '${{ github.event.inputs.deployCommit }}')
            }
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-test-webeditor.yml
          name: webeditor
          path: github1s/dist
      - run: ls -alth github1s/dist
